name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Sys-Dependencies
      run: sudo apt-get install -y libudev-dev
    - name: Dependencies
      run: cargo install probe-rs --features cli
    - name: Toolchain
      run: rustup target add thumbv6m-none-eabi thumbv7m-none-eabi thumbv7em-none-eabi thumbv7em-none-eabihf
    - name: Build
      run: cargo build --verbose
